# Generated by Django 4.1.1 on 2022-10-18 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_kotxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotxea.kotxea')),
            ],
        ),
    ]
